///////////////////////////////////////////////////////
/// SIMPLE DIFFUSE COLOR VERTEX PROGRAM ////////////
///////////////////////////////////////////////////////

void main(	float4 position : POSITION,
			float3 color : COLOR,
			float3 uv	  : TEXCOORD0,
		   			  
			out float4 oPosition	: POSITION,
			out float3 oColor		: COLOR,
			out float3 oUv			: TEXCOORD0,
						  
			uniform float4x4 worldViewProj)
{
	oPosition = mul(worldViewProj, position);

	oColor = color;
		 	
	oUv = uv;
}