///////////////////////////////////////////////////////
/// SPECULAR BUMPMAPPING 2D FRAGMENT PROGRAM //////////
///////////////////////////////////////////////////////

void main(float4 pos : POSITION, //in projection space
		  float3 uv : TEXCOORD0, //in object space
		              
		  out float4 oColor : COLOR,
            
		  uniform sampler2D ScreenBuffer : TEXUNIT0)
{
	float4 Col = tex2D(ScreenBuffer,uv);
	
	oColor = Col;
}