var text = new Array
(
	"Penumbra Manual",
	"MANUAL",
	"Introduktion",
	"Penumbra är ett smygande skräckspel som bygger mycket på stämmning och utforsking. Det är inget spel som man ska rusa igenom och om det är möjligt ska belysningen dämpas. Man ska även tänka på att de flesta faror kan undvikas med lite list.",
	"Kontroller",
	"Penumbra använder sig utav standard förstapersons kontroller för styra spelaren. Dessa är följande:",
	"W,A,S och D",
	"Rör spelaren framåt, bakåt, vänster och höger.",
	"Shift",
	"Hålls inne för springa.",
	"Control",
	"Håll nere för att ducka. Kan även bara trycka för att växla mellan ståendes/duckandes. Detta kan ställas in i options.",
	"Mellanslag",
	"Får spelaren att hoppa.",
	"Tab",
	"Öppnar inventory, mer om detta nedan.",
	"R",
	"Växlar mellan vanligt och Interact Mode. Mer om detta under interaction.",
	"Mus",
	"Rör på huvudet.<BR>Rör saker som man interagerar med.",
	"Vänster mus",
	"Interagera med föremål i spelet<BR>Väljer val i menyer.<BR>Kasta förmål (tex dynamit).",
	"Höger mus",
	"Titta på föremål i spelet<BR>Avbryter val.<BR>Kastar/puttar saker man håller.",
	"Q och E",
	"Får spelaren att luta sig åt vänster och höger. Kan vara bra för att kika runt hörn.",
	"F",
	"Snabbknapp för att sätta av och på ficklampan (Flashlight).",
	"G",
	"Snabbknapp för att sätta av och på lysstaven (Glowstick).",
	"N",
	"Snabbknapp för att öppna anteckningsblocket (Notebook).",
	"P",
	"Snabbknapp för att se personliga anteckingar (Personal Notes).",
	"1,2,3,4 och 5",
	"Inventory:s snabbknappar, används för att snabbt kunna använda ett item. Läs mer om det nedan.",
	"Escape",
	"Öppnar huvudmenyn.<BR>Skippa intro.<BR>Gå bakåt i menyer, anteckningsblock och inventory.",
	"Huvudmeny",
	"Huvudmenyn är det första men ser när spelet startar och kan även tas fram under spelets gång med Escape.",
	"Navigering sker med vänster musknapp genom att klicka på de olika valmöjligheterna. I Options klickar man på namnet till vänster om ':' för att ändra inställning. Vänster musknapp ändrar inställning uppåt och höger musknapp ändrar nedåt.",
	"Interaktion",
	"I stort sätt all interaktion i Penumbra sker på ett fysisk realistiskt sätt. När man kan interagera med något så dyker det upp en ikon på skärmen.<BR> För att lättare kunna interagera kan man växla till Interact Mode med R. I detta läge är det lättare att styra saker man håller i, samt att interagera med små saker.<BR> Genom att trycka på vänster musknapp så håller man tag i en sak. Man släpper sedan saken genom att släppa musknappen. När man håller i något så kan man kasta det med höger musknapp om man så vill.<BR>Tänk också på att man kan bli tvungen att ducka för att nå vissa saker på golvet.<BR>Följande ikoner förekommer:",
	"Inget att interagera med. Denna syns bara i Interact Mode.",
	"Föremålet går att titta på. Observera att förmålet också kanske går att interagera med, men att man är för långt borta.",
	"Föremålet går att interagera med. Det kanske även går att titta på föremålet. Ögon-ikonen visas bara när man är för långt bort för att kunna interagera.",
	"Visas när man interagerar fysiskt med något föremål. Denna visas bara när interaktions knappen är intryckt.",
	"Man är för långt ifrån för att interagera med ett föremål och det går heller inte att titta på föremålet. Visas bara i Interact Mode.",
	"Förmålet kan plockas upp och läggs till i inventory vid interaktion.",
	"Detta betyder att föremålet är en dörr. Vid interaktion öppnas den och man går in till ett nytt rum.",
	"Inventory",
	"Inventory uppenbaras när man trycker på Tab. <BR> För att använda föremålen i den så dubbelklickar man på dem. Man kan dra runt dem genom att klicka på förmålet och göra en \"drag n' drop\". Det går även att försöka kombinera två föremål genom att dra det ena över det andra. Vissa föremål kan slängas genom att dra dem utanför luckorna.",
	"Detta visar hur mycket batteri man har. Saker som ficklampan drar batteri när de är igång. Man ökar mätaren genom att plocka upp batterier.",
	"Detta är snabbluckorna. När ett item är lagd i en av dessa används de i spelet genom att trycka på siffran (1,2,3,4 eller 5) som står i luckan.",
	"Viktiga föremål",
	"<B>Anteckningsblock (Notebook)</B><BR>Här samlas alla texter som hittas samt diverse anteckingar om saker av intresse. Mer om detta nedan.",
	"<B>Ficklampa (Flashlight)</B><BR>Används undersöka mörka områden. Använder batterier och bör användas sparsamt.",
	"<B>Lysstav (Glowstick)</B><BR>Ger ljus åt spelaren, sämre än ficklampan men drar ingen ström.",
	"<B>Signalljus (Flare)</B><BR>Används för att lysa upp rum. Kastas längre ju längre knappen hålls inne.",
	"<B>Dynamit (Dynamite)</B><BR>Kan användas för att spränga saker, dock inte så bra som försvars vapen. Kastas längre ju längre knappen hålls inne.",
	"<B>Smärtstillande (Painkillers)</B><BR>Ger full hälsa åt spelaren.",
	"Anteckningsblock",
	"Här kan man först välja om man vill se upphittade texter (Notes) eller personliga anteckingar (Personal Notes). Man navigerar mellan de olika sakerna genom att klicka på dem. Vissa texter man hittar består av flera sidor. Man kan bläddra fram och tillbaka genom att trycka på pilarna i nedre hörnen. Man går tillbacka antingen med Tab, N, P eller Escape.",
	"Hälsa",
	"Det finns flera saker i spelvärlden som kan ge en sämre hälsa. När man börjar få dålig hälsa så antyds detta med visuella och hörbara medel. Man återhämtar sig långsamt då man har dålig hälsa.",
	"Contact",
	"Hälsa på oss här:",
	"for frågor, feedback, support eller annat:",
	"Credits",
	"Huvudteamet som utvecklat Penumbra är:",
	"Grafik.",
	"Ljud, design, scripting.",
	"Grafik, design.",
	"Programmering, design.",
	"Under projekets gång har följande personer hjälpt till:",
	"Modeller och texturer.",
	"Modeller och nån textur.",
	"Modeller.",
	"Intro bilder",
	"Ambient musik",
	"Titel musik och intro musik",
	"Intro röst",
	"Annan hjälp:",
	"Fysik",
	"Beta testare har varit:",
	"De som hjälpt till med att göra allt internationellt:",
	"Spansk version",
	"Tysk version",
	"Italiensk version"
);
