var text = new Array
(
	"Manuale di Penumbra",
	"MANUALE",
	"Introduzione",
	"Penumbra è un gioco a tinte horror focalizzato sulla furtività e sull'esplorazione. Non è un gioco dove si corre a destra e a sinistra. E' vivamente consigliato spegnere tutte le luci prima di giocare.",
	"Controlli ",
	"Penumbra usa i comandi standard dei giochi in prima persona. Questi sono quelli preimpostati (ma sono liberamente modificabili nelle opzioni):",
	"W,A,S o D",
	"Muovono il protagonista.",
	"Shift",
	"Tenere premuto per correre.",
	"Control",
	"Dipende dal modo in cui è settato. Può essere premuto per mantenersi accucciati oppure deve essere mantenuto premuto per rimanere accucciati.",
	"Space",
	"Fa compiere un salto al protagonista.",
	"Tab",
	"Apre l'inventario. Questo aspetto verrà approfondito più avanti.",
	"R",
	"Passa da modalità esplorazione a modalità interazione. Quest'ultima verrà spiegata più avanti.",
	"Mouse",
	"Muove la visuale.<br>Muove gli oggetti afferrati.",
	"Pulsante sinistro del mouse",
	"Interagisce con gli oggetti nel gioco.<br>Seleziona le opzioni nei menù.<br>Lancia gli oggetti (tipo la dinamite).",
	"Pulsante destro del mouse",
	"Esamina gli oggetti dello scenario.<br>Cancella le selezioni.<br>Lancia gli oggetti afferrati.",
	"Q o E",
	"Fa che il giocatore si pieghi a destra o a sinistra. Utile per affacciarsi dagli angoli.",
	"F",
	"Accende/spegne la torcia.",
	"G",
	"Accende/spegne la bacchetta fluorescente.",
	"N",
	"Apre il taccuino.",
	"P",
	"Apre le note personali.",
	"1,2,3,4 o 5",
	"Tasti di scelta rapida per l'inventario. Questo particolare verrà spiegato in dettaglio più avanti.",
	"Esc",
	"Apre il menù principale.<br>Salta il filmato introduttivo.<br>Torna indietro nei menù, nell'inventario e nel taccuino.",
	"Menù principale",
	"Il menù principale è la prima cosa che appare quando si lancia il gioco. Può essere raggiunto anche durante il gioco premendo il tasto 'Esc'.",
	"Il menù è esplorabile cliccando con il tasto sinistro del mouse sulle differenti opzioni. Per cambiare i settaggi nel menù opzioni basta cliccare sul testo alla sinistra di \":\".<br>Alcune opzioni possono essere aumentate o diminuite usando i tasti destro e sinistro del mouse. Il tasto sinistro aumenta i valori, il destro li diminuisce.",
	"Interazione ",
	"Quasi tutte le interazioni in Penumbra avvengono in un modo fisicamente realistico. Quando si può interagire con qualcosa, appare un'icona sullo schermo.<br>Per un'interazione più facile, si può passare alla modalità interazione premendo il tasto 'R'. Questa modalità rende più facile controllare le cose e interagire anche con i più piccoli oggetti.<br>Si può afferrare un oggetto premendo il tasto sinistro del mouse e lasciarlo cadere smettendo di tenere premuto. Se si sta tenendo qualcosa, è possibile lanciarla premendo il tasto destro del mouse.<br>E' importante ai fini del corretto proseguimento nel gioco sottolineare che per raccogliere le cose per terra è necessario chinarsi.<br>Compariranno a video le seguenti icone:",
	"Niente con cui interagire. Visibile solo in modalità interazione.",
	"Il giocatore può esaminare l'oggetto. Probabilmente è possibile anche interagire, ma si è troppo lontani.",
	"E' possibile interagire con l'oggetto. Lo si può anche esaminare, ma bisogna allontanarsi affinchè l'occhio compaia.",
	"Appare quando il giocatore sta interagendo con oggetti fisici.",
	"L'oggetto è troppo lontano e non è possibile esaminarlo. Visibile solo nella modalità interazione.",
	"Interagendo, l'oggetto viene raccolto e riposto nell'inventario.",
	"Significa che l'oggetto è una porta. Interagendo, la porta si aprirà e si passerà alla stanza successiva.",
	"Inventario",
	"L'inventario appare premendo il tasto 'TAB'.<br>I diversi oggetti nell'inventario vengono usati cliccando due volte su di essi con il tasto sinistro del mouse. Tenendo premuto lo stesso tasto, è possibile afferrarli e trascinarli. Questa operazione può essere utile per combinare gli oggetti afferrandoli e trascinandoli su altri. Alcuni oggetti possono anche venire abbandonati afferrandoli, trascinandoli fuori dall'inventario e rilasciando il pulsante.",
	"Mostra l'energia rimasta nelle batterie. Oggetti come la torcia consumano le batterie quando sono attivi. La percentuale viene incrementata raccogliendo altre batterie.",
	"Slot di selezione rapida. Quando un oggetto viene trascinato qui, può essere usato pigiando sul numero corrispondente (1,2,3,4 o 5).",
	"Oggetti importanti",
	"<b>Taccuino</b><br>Tutte le note raccolte durante il gioco sono riportate qui. Include anche note personali di cose particolarmente interessanti. Di più sull'argomento più avanti.",
	"<b>Torcia</b><br>Utile quando si esplorano aree buie. Consuma le batterie, per cui va usata con parsimonia.",
	"<b>Bacchetta fluorescente</b><br>Dà al giocatore una luce fioca. Non efficace come la torcia, ma non consuma le batterie.",
	"<b>Bengala</b><br>Utile per illuminare stanze. Il protagonista lo lancia tanto più lontano quanto più a lungo si tiene premuto il tasto destro del mouse.",
	"<b>Dinamite</b><br>Può essere usata per far saltare in aria qualcosa, ma non è molto utile per difendersi. Il protagonista la lancia tanto più lontano quanto più a lungo si tiene premuto il tasto destro del mouse.",
	"<b>Antidolorifici</b><br>Ripristinano completamente la salute del protagonista.",
	"Taccuino",
	"Per prima cosa bisogna scegliere se si vogliono leggere le note personali oppure quelle raccolte durante il gioco. Le differenti scelte si compiono cliccando sul testo. Alcuni testi sono composti da diverse pagine, che possono essere viste tutte cliccando sulle frecce negli angoli in basso a destra e a sinistra. Si può uscire dal taccuino premendo uno tra i tasti 'Tab', 'N', 'P' o 'Esc'.",
	"Salute",
	"Ci sono diverse cose nel gioco che possono far diminuire la salute del giocatore. Quando il livello di salute arriva ad uno stato critico, il giocatore se ne accorgerà grazie a degli effetti visivi e sonori. La salute comunque si recupera lentamente con il passare del tempo.",
	"Contatti",
	"Vienici a trovare su:",
	"Per qualunque domanda, commento o supporto puoi trovarci su:",
	"Credits",
	"Il team di sviluppo di Penumbra è composto da:",
	"Grafica",
	"Suoni, musica, design e scripting",
	"Grafica, design",
	"Programmazione, design",
	"Le seguenti persone sono state di grande aiuto:",
	"modelli e textures",
	"modelli e alcune texture",
	"modelli",
	"Immagini del filmato iniziale.",
	"Musiche degli ambienti",
	"Musica dei titoli",
	"Voce del filmato d'apertura",
	"Altri aiuti:",
	"Fisica",
	"Beta testers:",
	"Internazionalizzazione:",
	"Versione espagnola",
	"Versione tedesca",
	"Versione italiana",
	"Versione francesa"
);
