var text = new Array
( 
	"Manuel de Penumbra",
	"MANUEL",
	"Introduction",
	"Penumbra est un jeu d'horreur basé sur l'angoisse et l'exploration. <br>Eteignez la lumière avant de jouer.",
	"Controles",
	"Penumbra utilise les controles classiques de jeu à la 1ère personne. Par défaut (Vous pouvez les changer dans les options):",
	"Z,Q,S et D",
	"Pour se déplacer.",
	"Shift",
	"Pressez pour courrir.",
	"Control",
	"Suivant le mode actuel, alterne se baisser/se lever ou en position basse quand la touche est pressée.",
	"Espace",
	"Pour sauter.",
	"Tabulation",
	"Ouvre la fenêtre d'inventaire.",
	"R",
	"Alterne les modes déplacement et interactif.",
	"Souris",
	"Tourne la tête.<br>Déplace les objets pris.",
	"Bouton gauche de la souris",
	"Interagit avec les objets.<br>Selectionne le menu options.<br>Jetter (par exemple la dynamite).",
	"Bouton droit de la souris",
	"Examine un objet.<br>Annule la selection.<br>Jette les objets pris.",
	"A et E",
	"Se pencher à droite/gauche. Util pour observer sans être vu.",
	"F",
	"Allume/eteinds la lampe torche.",
	"G",
	"Allume/eteinds le glowstick.",
	"N",
	"Ouvre le bloc-note.",
	"P",
	"Ouvre les notes personnelles.",
	"1,2,3,4 et 5",
	"Raccouris clavier pour l'inventaire. Explications un peu plus loin.",
	"Echape",
	"Aller dans le menu principal.<br>Passer l'introduction.<br>Aller dans la page précédente des menus, inventaire et du blocnote.",
	"Menu principal",
	"Le menu principal est la première chose que vous voyez quand vous lancez le jeu. Il est aussi possible d'y aller pendant le jeu quand vous appuyez sur ECHAPE.",
	"La navigation se fait que vous faites un clique gauche dans les differents choix. Pour changer une options dans le menu options, cliquez sur le texte a gauche des \":\"<br>Certaines options peuvent être incrémentées et decrémentées en utilisant les boutons droit et gauche de la souris.",
	"Interaction",
	"Toutes les interactions dans Penumbra sont physiquement réalistes. Quand vous pouvez <br> interagir avec un object, une icône apparaît à l'écran.<br> Pour une interaction plus facile, vous pouvez passer en mode interaction en appuyant sur R. Ca rend l'interaction plus facile avec les petits objets. Vous pouvez prendre un objet en appuyant sur le bouton gauche de la souris et le laisser tomber en relachant le bouton. Si vous avez un objet et que vous voulez le lancer, appuyez sur le bouton droit de la souris. Il est possible que vous deviez vous baisser pour ramasser des objets au sol.<br> Les icônes suivant peuvent être visibles:",
	"Vous ne pouvez interagir avec rien. Seulement en mode interaction.",
	"Vous ne pouvez par examiner un objet. Vous pouvez interagir avec mais il est trop loin pour être examiné.",
	"Il est possible d'interagir avec l'objet. Il est aussi possible de l'examiner. L'icône d'oeil est seulement visible quand l'objet est hors de porté. Affiché quand vous interagissez avec l'objet.",
	"Affiché quand le joueur interagit sur des objets physiques.",
	"L'objet est trop loin et il n'est pas possible de l'examiné. Seulement en mode intéraction.",
	"L'objet est pris et ajouté à l'inventaire.",
	"Cela signifie que l'objet est une porte.",
	"Inventaire",
	"L'inventaire est visible grâce à la touche TAB.<br>Les différents objets de l'inventaire sont utilisable en les double cliquant. Si vous restez appuyé dessus avec le bouton gauche de la souris, vous pouvez essayer de combiner des objets en les déplacant l'un sur l'aitre. Vous pouvez les jeter en les glissant hors de l'inventaire.",
	"Affiche la quantité de batterie disponible pour la lampe torche. Les objets comme la lampe torche consomment de l'energie. La quantité d'energie disponible augmente si vous trouvez des piles.",
	"Ce sont les raccourcis clavier. Quand des objets sont dans ces espaces, ils peuvent être utilisé en appuyant sur 1,2,3,4 et 5.",
	"Objets Importants",
	"<b>Blocnote</b><br>Toutes les notes trouvées dans le jeu sont répertoriées ici. Le blocnote inclus aussi des notes personnelles spécialement interressantes.",
	"<b>Lampe torche</b><br>Utile pour observer les endroits sombres. Elle consomme de l'énergie et ne doit pas être utilisée trop longtemps.",
	"<b>Glowstick</b><br>Il n'est pas aussi efficace que la lampe torche mais n'utilise pas de piles.",
	"<b>Fusée éclairante</b><br>Utile pour certaines pièces. Plus vous restez appuyez sur le bouton gauche de la souris, plus elle est envoyée loin.",
	"<b>Dynamite</b><br>Pas très utile en arme deffensive. Plus vous appuyez longtemps le bouton gauche de la souris, plus vous la lancez loin.",
	"<b>Anesthésiant</b><br>Redonne de la santé.",
	"Blocnote",
	"D'abords, vous choisissez si vous voulez voir les notres trouvées ou les notes personnelles. Le choix se fait en cliquant sur le texte. Certains textes font plusieurs pages. Vous pouvez passer d'une page à un eautre en cliquant sur les flèches en bas a gauche et droite. sortez du blocnote en pressant au choix les touches TAB, N, P ou Echape.",
	"Santé",
	"Il y a plusieurs choses qui peuvent porter atteinte à votre santé. Des alertes visuelles et audio arrivent quand votre santé devient critique. La santé s'améliore petit à petit avec le temps.",
	"Contact",
	"Venez nous rendre visite:",
	"Pour des questions et du support, visitez:",
	"Credits",
	"l'équipe de Penumbra est composée de:",
	"Graphisme",
	"Soun, design et scripts",
	"Graphisme, design",
	"Programmation, design",
	"Les personnes suivantes nous ont aidé:",
	"Modèles et textures",
	"Modèles et quelques textures",
	"Modèles",
	"Images d'introduction",
	"Musique d'ambiance",
	"Musique principale et musique scénaristique",
	"Voix d'introduction",
	"Autre:",
	"Physique",
	"Testeurs des versions Betas:",
	"Les personnes suivantes ont contribué aux traductions:",
	"Version Espagnole",
	"Version Allemande",
	"Version Italienne",
	"Version Française"
);
