///////////////////////////////////////////////////////
/// SIMPLE DIFFUSE COLOR VERTEX PROGRAM ////////////
///////////////////////////////////////////////////////

void main(	float4 position : POSITION,
					  
			out float4 oPosition	: POSITION,
			//out float3 oColor		: COLOR,
						  
			uniform float4x4 worldViewProj,
			uniform float3 lightPosition)
{
	position.xyz -= lightPosition*(1-position.w);
	
	oPosition = mul(worldViewProj, position);
    //oColor = float3(0.1,0,0.1);
}