var text = new Array
(
	"Penumbra Manual",
	"ANLEITUNG",
	"Einleitung",
	"Penumbra ist ein Horror Adventure das sich auf Entdecken und Schleichen Konzentriert. Es ist kein Spiel wo man nicht einfach durchrennen	kann! Und wenn es m&ouml;glich ist schalte das Lichtaus.",
	"Steurung",
	"Penumbra	nutzt die Standard Ego-Shooter Steurung. Dies sind die Standard	Funktionen diese k&ouml;nnen im Men&uuml; unter Options ge&auml;ndert	werden!",
	"W,A,S,D",
	"Bewegt die Figur.",
	"Shift",
	"Halten zum Rennen.",
	"STRG (Steurung)",
	"Ducken/Aufstehen.",
	"Leertaste",
	"Springen.",
	"Tab",
	"Inventar.",
	"R",
	"Interaktions Modus.",
	"Maus",
	"Umschauen ; Gegenst&auml;nde in Hand bewegen.",
	"Linke Maustaste",
	"Interagieren; Optionen Im Men&uuml; Ausw&auml;hlen; Gegenst&auml;nde werfen.",
	"Rechte Maustaste",
	"Untersuchen von Objekten; Aktion Abbrechen, Ausgew&auml;hlte Gegenst&auml;nde fallen lassen.",
	"Q, E",
	"Nach Links/Rechts lehnen.",
	"F",
	"Taschenlampe.",
	"G",
	"Leuchtstab.",
	"N",
	"Notizbuch.",
	"P",
	"Pers&ouml;nliche Notizen.",
	"1,2,3,4 und 5",
	"Kurztasten f&uuml;r das Inventar.",
	"Escape",
	"Hauptmen&uuml; w&auml;hrend Spiel &ouml;ffnen, In Men&uuml;s zur&uuml;ck.",
	"Hauptmen&uuml;",
	"Das Hauptmen&uuml; ist das erste was man beim Starten des Spiels	sieht. Du kannst in dieses auch w&auml;hrend des Spielens	gelangen indem du ESC dr&uuml;ckst.",
	"Um zu Navigieren klicke auf die Men&uuml;punkte mit der Linken Maustaste. In den Optionen kannst du die Einstellungen &auml;ndern indem du auf den Text links daneben klickst!<BR>Du kannst die Optionen in verschiedene	Richtungen nutzen indem du die Linke sowie Rechte Maustaste	benutzt.",
	"Interaktion",
	"Alle Interaktionen in Penumbra h&auml;ngen mit Physik zusammen wenn eine Interaktion	verf&uuml;gbar ist wird dies durch ein Symbol angezeigt.<BR>Um leichte zu Interagieren dr&uuml;cke R dies &ouml;ffnet den	Interaktionsmodus um leichter mit Objekten zu agieren!<BR>Du kannst Gegenst&auml;nde mit der Linken Maustaste aufheben und diese durch loslassen fallen lassen. Wenn du einen Gegenstand in	der Hand hast dr&uuml;cke die Rechte Maustaste um ihn zu werfen.<BR>Merke das du dich ducken musst um an Dinge auf den Boden zu gelangen.<BR>Diese Symbole werden sichtbar bei Interaktionen:",
	"Nichts zum Interagieren. Nur sichtbar im Interaktionsmodus.",
	"Objekt untersuchen. M&ouml;glicherweise kann man	mit dem Objekt interagieren nur man ist zu weit weg!",
	"Es ist m&ouml;glich das man mit diesem Objekt interagieren kann. Das Augensymbol wird nur angezeigt wenn das Objekt au&szlig;er Reichweite ist.",
	"Zeichen daf&uuml;r das man mit einem Physikalischen Objekt agiert.",
	"Das Objekt ist zu weit weg und man kann es nicht untersuchen. Nur im Interaktionsmodus sichtbar!",
	"Das Objekt ist aufgehoben und zum Inventar	hinzugef&uuml;gt!.",
	"Zeichen f&uuml;r eine T&uuml;r",
	"Inventar",
	"Das Inventar wird mit TAB ge&ouml;ffnet<BR>Die verschiedenen Objekte	werden mit einem Doppelklick der linken Maustaste benutzt. Wenn	du die linke Maustaste h&auml;ltst kannst du das Objekt	verschieben. Dies ist n&uuml;tzlich um Objekte zu kombinieren. Manche Gegenst&auml;nde k&ouml;nnen aus dem Inventar geworfen werden indem man es aus dem Inventar schiebt!",
	"Dies zeigt den Batteriestand der Taschenlampe.",
	"Dies sind die Schnelltasten Bl&ouml;cke hier kann ein Gegenstand reingezogen werden und sp&auml;ter mit 1,2,3,4,5 ausgew&auml;hlt werden!",
	"Wichtige Gegenst&auml;nde",
	"<b>Notizbuch</b><br>Alle Notizen die du findest werden hier abgelegt auch wichtige Pers&ouml;nliche Notizen sind hier zu finden!",
	"<b>Taschenlampe</B><BR>Sehr n&uuml;tzlich in	dunklen R&auml;umen. Braucht aber Batterien!",
	"<b>Leuchstab</B><BR>Gibt dem Spieler eine unendlich lange Lichtquelle!",
	"<b>Fackel</b><BR>N&uuml;tzlich um ganze R&auml;ume zu beleuchten. (Wurfgegenstand)",
	"<B>Dynamit</B><BR>Gut um Gegenst&auml;nde in die Luft zu jagen (Wurfgegenstand)",
	"<B>Schmerzstillendes Mittel</B><BR>Regeniert die Spieler Energie.",
	"Notizbuch",
	"Im	Notizbuch werden alle wichtigen Notizen deinerseits angezeigt. Du gelangst mit TAB,N und P dorthin (P ist nur f&uuml;r Pers&ouml;nliche	Notizen).",
	"Energie",
	"Es gibt mehrere Dinge die einem Schaden zuf&uuml;gen k&ouml;nnen wenn die Energie nicht so gut ist wird dies Grafisch sowie per Audio dargestellt.",
	"Kontakt",
	"Besuch uns	unter:",
	"Fragen, Feedback und Support:",
	"Credits",
	"Das Hauptteam hinter Penumbra sind:",
	"Graphics",
	"Sound, design and scripting",
	"Graphics, design",
	"Programming, design",
	"Diese Leute waren uns eine gro&szlig;e	Hilfe:",
	"Models and textures",
	"Models and some textures",
	"Models",
	"Intro images",
	"Ambient music",
	"Title music and intro music",
	"Intro voice",
	"Weitere Hilfe:",
	"Physics",
	"Beta Testers:",
	"Diese Leute haben um die Internationalisierung zu machen geholfen:",
	"Spanische Version",
	"Deutsche Version",
	"Italienische Version",
	"Franzosische Version"
);
	