var text = new Array
(
	"Manual del juego Penumbra",
	"MANUAL DEL JUEGO",
	"Introducci&oacute;n",
	"Penumbra es un denso juego de terror, que hace &eacute;nfasis en el sigilo y la exploraci&oacute;n. No es un juego que te puedas terminar simplemente corriendo.<br>Si te es posible, apaga las luces antes de empezar a jugar (recomendado).",
	"Controles",
	"Penumbra usa los controles usuales en un juego en primera persona. Estos son los que hay por defecto (puedes cambiarlos en las opciones):",
	"W,A,S y D",
	"Movimiento.",
	"May&uacute;sculas",
	"Mantener pulsado para correr.",
	"Control",
	"Dependiendo del modo elegido, puede cambiar el estado entre agachado/levantado, o puede necesitar estar pulsado para manternerte agachado.",
	"Espacio",
	"Salto.",
	"Tab",
	"Abre el inventario. Informaci&oacute;n detallada m&aacute;s adelante.",
	"R",
	"Cambia entre el modo Normal y el modo Interacci&oacute;n. El modo Interacci&oacute;n se explica m&aacute;s adelante.",
	"Rat&oacute;n",
	"Orientaci&oacute;n de la vista.<br>Movimiento del objeto agarrado actualmente.",
	"Bot&oacute;n izquierdo",
	"Interacci&oacute;n con objetos del juego.<br>Selecci&oacute;n de opciones en men&uacute;s.<br>Lanzamiento de objetos (ej: dinamita).",
	"Bot&oacute;n derecho",
	"Examinar objetos del juego.<br>Cancelar selecci&oacute;n.<br>Lanzamiento del objeto agarrado.",
	"Q y E",
	"Inclinaci&oacute;n a la izquierda y derecha. &Uacute;til para asomarse por esquinas.",
	"F",
	"Enciende/apaga la linterna.",
	"G",
	"Enciende/apaga la barrita fluorescente.",
	"N",
	"Muestra el cuaderno de notas.",
	"P",
	"Muestra las notas personales.",
	"1,2,3,4 y 5",
	"Teclas de acceso directo del inventario. Explicado con detalle m&aacute;s adelante.",
	"Escape",
	"Muestra el men&uacute; principal.<br>Salta la intro.<br>Vuelve a la pantalla anterior en men&uacute;s, inventario y cuaderno de notas.",
	"Men&uacute; principal",
	"El men&uacute; principal es lo primero que aparece al cargar el juego, tambi&eacute;n puede mostrarse durante el juego pulsando escape.",
	"Para navegar por el men&uacute; se usa el rat&oacute;n y se hace click con el bot&oacute;n izquierdo en las diferences opciones. Para cambiar el valor de una opci&oacute;n debes hacer click en el texto a la izquierda del car&aacute;cter \":\". <br> Algunas opciones tienen un valor que puede hacerse incrementar o decrementar (ej: resoluci&oacute;n), por medio de los botones izquierdo y derecho respectivamente.",
	"Interacci&oacute;n",
	"Casi toda interacci&oacute;n en Penumbra se realiza de una manera f&iacute;sicamente realista. Cuando puedas interactuar con algo, aparecer&aacute; un icono en la pantalla.<br>Para facilitar la interacci&oacute;n, se puede cambiar al modo Interacci&oacute;n pulsando R. Este modo hace mucho m&aacute;s f&aacute;cil el control y la interacci&oacute;n con objetos peque&ntilde;os. <br>Para agarrar un objeto, pulsa el bot&oacute;n izquierdo del rat&oacute;n y para soltarlo, deja de pulsar. Si est&aacute;s agarrando algo, puedes lanzarlo apretando el bot&oacute;n derecho mientras mantienes pulsado el izquierdo.<br> Ten en cuenta que puede que tengas que agacharte para recoger cosas que est&eacute;n en el suelo.<br>Los iconos que pueden aparecer son los siguientes:",
	"No hay nada con qu&eacute; interactuar. S&oacute;lo visible en modo Interacci&oacute;n.",
	"El objeto puede ser examinado. Ten en cuenta que es posible que pueda interactuarse con el objeto, pero que est&aacute; demasiado lejos para hacerlo.",
	"Es posible interactuar con el objeto. Tambi&eacute;n es posible que pueda ser examinado, el icono del ojo s&oacute;lo se muestra cuando el objeto est&aacute; fuera de tu alcance.",
	"Se muestra cuando se est&aacute; interactuando con un objeto f&iacute;sico (ej: cajas, puertas... la mayor&iacute;a de objetos).",
	"El objeto est&aacute; demasiado lejos y no es posible examinarlo. S&oacute;lo visible en modo Interacci&oacute;n.",
	"Cuando este icono aparece, indica que el objeto se puede recoger. Al hacer clic, el objeto es recogido y a&ntilde;adido al inventario.",
	"Este icono indica que el objeto es una puerta. Al interactuar, la puerta se abre y el jugador pasa a la habitaci&oacute;n a la que &eacute;sta conduce.",
	"Inventario",
	"El Inventario se abre al pulsar la tecla Tabulador. <br>Los diferentes objetos del inventario se usan haciendo doble clic sobre ellos con el bot&oacute;n izquierdo del rat&oacute;n. Si mantienes pulsado el bot&oacute;n izquierdo del rat&oacute;n puedes arrastrarlo.Esto sirve para combinar objetos arrastrando y soltando uno encima del otro. Algunos objetos tambi&eacute;n pueden lanzarse arrastr&aacute;ndolos fuera del inventario y soltando el bot&oacute;n.",
	"Esto indica el nivel de bater&iacute;a. Objetos como la linterna consumen energ&iacute;a cuando est&aacute;n funcionando. El nivel aumenta recogiendo pilas.",
	"&Eacute;stas son las ranuras de acceso r&aacute;pido. Cuando un objeto est&aacute; en una de &eacute;stas, puede usarse pulsando el n&uacute;mero (1,2,3,4 o 5) que corresponda a la ranura.",
	"Objetos Importantes",
	"<b>Cuaderno de notas</b><br>Todas las notas que se van encontrando en el juego se a&ntilde;aden aqu&iacute;. Tambi&eacute;n incluye notas personales sobre cosas de especial inter&eacute;s. M&aacute;s informaci&oacute;n abajo.",
	"<b>Linterna</b><br>Es &uacute;til para investigar zonas oscuras. Gasta pilas y no deber&iacute;a ser usada m&aacute;s que lo estrictamente necesario.",
	"<b>Barrita fluorescente</b><br>Proporciona una tenue luz al jugador. No ilumina tanto como la linterna, pero no consume nada.</td>",
	"<b>Bengala</b><br>&Uacute;til para iluminar habitaciones. Cuanto m&aacute;s tiempo se mantenga pulsado el bot&oacute;n izquierdo, m&aacute;s lejos se lanzar&aacute;.",
	"<b>Dinamita</b><br>Puede usarse para demoler cosas, no es muy &uacute;til como arma defensiva. Al igual que la bengala, cuanto m&aacute;s tiempo se pulse el bot&oacute;n izquierdo, m&aacute;s lejos se lanzar&aacute;.",
	"<b>Analg&eacute;sicos</b><br>Restaura completamente la salud del jugador.",
	"Cuaderno de Notas",
	"Primero has de elegir si quieres ver las notas personales o las notas encontradas.Las distintas opciones son seleccionadas haciendo clic encima del texto. Algunos textos ocupan varias p&aacute;ginas, puedes navegar por ellas presionando las flechas en las esquinas inferior derecha e izquierda. Para salir del cuaderno, puedes presionar Tab, N, P o Escape.",
	"Salud",
	"En el juego se pueden dar situaciones que hacen que el nivel de salud del jugador se vea reducido. Cuando este nivel baja demasiado, se producen efectos visuales y sonoros para avisarte. El nivel de salud sube lentamente a lo largo del tiempo.",
	"Contacto",
	"Ven a vernos a:",
	"Para cualquier pregunta, comentarios y soporte visita (en ingl&eacute;s):",
	"Cr&eacute;ditos",
	"El Equipo Principal tras Penumbra:",
	"Gr&aacute;ficos",
	"Sonido, m&uacute;sica, dise&ntilde;o y scripting",
	"Gr&aacute;ficos, dise&ntilde;o",
	"Programaci&oacute;n, dise&ntilde;o",
	"Las siguientes personas han sido de gran ayuda:",
	"Modelos y texturas",
	"Modelos y algunas texturas",
	"Modelos",
	"Im&aacute;genes de la intro",
	"M&uacute;sica ambiental",
	"M&uacute;sica de la pantalla de t&iacute;tulo",
	"Voz de la intro",
	"Otros agradecimientos:",
	"F&iacute;sica",
	"Beta Testers:",
	"Las siguientes personas han ayudado a la internacionalizaci&oacute;n:",
	"Versi&oacute;n en espa&ntilde;ol",
	"Versi&oacute;n en alem&aacute;n",
	"Versi&oacute;n en italiano",
	"Versi&oacute;n en francés"
);
