var text = new Array
( 
	"Penumbra Manual",
	"MANUAL",
	"Introduction",
	"Penumbra is a slow paced horror game which focuses on sneaking and exploration. It is not a game one can run through.<br>Also, if possible turn down the lights before playing.",
	"Controls",
	"Penumbra uses standard first person controls. These are the defaults (you can change them in options):",
	"W,A,S and D",
	"Moves the player.",
	"Shift",
	"Hold to run.",
	"Control",
	"Depending on which mode is set it can toggle crouch or it needs to be held to crouch.",
	"Space",
	"Makes the player jump.",
	"Tab",
	"Opens up the inventory. More information on this later on.",
	"R",
	"Toggle Normal- and InteractMode. InteractMode is explained later on.",
	"Mouse",
	"Moves the player head.<br>Move objects that are grabbed.",
	"Left mouse button",
	"Interact with objects in the game.<br>Selects options in menus.<br>Throws items (ie the dynamite).",
	"Right mouse button",
	"Examine game objects.<br>Cancels selections.<br>Throws grabbed objects.",
	"Q and E",
	"Makes the player lean left and right. Useful for peeking around corners.",
	"F",
	"Turns the flashlight on/off.",
	"G",
	"Turns the glowstick on/off.",
	"N",
	"Opens the notebook.",
	"P",
	"Opens the personal notes.",
	"1,2,3,4 and 5",
	"Shortcut keys for the inventory. This is explained in more detail later on.",
	"Escape",
	"Opens the main menu.<br>Skips intro.<br>Go backwards in menus, inventory and notebook.",
	"Main menu",
	"The main menu is the first thing seen when launching the game, it can also be reached during the game by pressing escape.",
	"Navigation is done by left clicking on the different choices. To change the setting in the option menu you will have to click on the text left of the \":\". <br>Some options can be increased and decreased and you do that by using left and right mouse button. Left mouse button increases values and right decreases.",
	"Interaction",
	"Almost all interaction in penumbra behaves in a physically realistic manner. When something can <br> be interacted with, an icon will appear on the screen.<br> For easier interaction, InteractMode can be used by pressing R. This mode makes it easier to control things and to interact with small objects. <br>You grab an object by pressing the left mouse button and let it go by releasing the button. If you are holding something, you can throw it away by pressing the right mouse button.<br> Note that you might have to crouch to reach things on the floor.<br> The following icons can be seen:",
	"Nothing to interact with. Only visible in InteractMode.",
	"The player can examine the object. Please note that it may be possible to interact with the object, but that it is too far away.",
	"It is possible to interact with the object. It might also be possible to examine the object, the eye-icon is only shown when object is out of reach. Is shown when the player is interacting with phyisical object.",
	"Is shown when the player is interacting with phyisical object.",
	"The object is too far away and it is not possible to examine it. Only shown in InteractMode.",
	"The object is picked and added to the inventory at interaction.",
	"This means the object is a door. When interacting the door is opened and the player enters a new room.",
	"Inventory",
	"The Inventory is shown when pressing Tab.<br>The different items in the inventory are used by double clicking with the left mouse button on them. If you hold down the left mouse button you can drag the item around. This can be used to combine items by simply dragging and dropping one over another. Some items can also be thrown by dragging them outside the inventory and releasing the button.",
	"This shows the amount of battery left. Items like the flashlight consume battery when they are active. The percentage is increased by picking up batteries.",
	"These are the shortcut slots. When an item is in one of these, it can be used by pressing the number (1,2,3,4 or 5) wich is seen in the slot.",
	"Important Items",
	"<b>Notebook</b><br>All notes that are found in the game are collected here. It also includes personal notes of especially interesting things. More on this below.",
	"<b>Flashlight</b><br>Is useful when investigating dark areas. It consumes batteries and should not be used too much.",
	"<b>Glowstick</b><br>Gives the player a faint light. Not as good as the flashlight but does not use any batteries.",
	"<b>Flare</b><br>Useful for lighting rooms. It is thrown further the longer the left mouse key is pressed.",
	"<b>Dynamite</b><br>Can be used to blow up stuff, not very useful as a defensive weapon though. It is thrown further the longer the left mouse key is pressed.",
	"<b>Painkillers</b><br>Gives the player full health.",
	"Notebook",
	"First you choose whether you want to look at notes found or personal notes. The different choices are selected by clicking on the text. Some text consists of several pages, you can navigate these by pressing the arrows in the lower left and right corners. The notebook can be exited by either pressing Tab, N, P or Escape.",
	"Health",
	"There are several things in the game world that can decrease the player health. When health starts getting bad this is hinted by visual and auditory effects. Health is also slowly increased over time.",
	"Contact",
	"Check us out at:",
	"For questions, feedback and support visit:",
	"Credits",
	"The Main Team behind penumbra are:",
	"Graphics",
	"Sound, design and scripting",
	"Graphics, design",
	"Programming, design",
	"The following people have been of great help:",
	"Models and textures",
	"Models and some textures",
	"Models",
	"Intro images",
	"Ambient music",
	"Title music and intro music",
	"Intro voice",
	"Other:",
	"Physics",
	"Beta Testers:",
	"The following people have contributed to internationalization:",
	"Spanish version",
	"German version",
	"Italian version",
	"French version"
);
